# Generated by Django 5.2.5 on 2025-08-09 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin (firm)'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rengine_dashboard.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'firm')},
            },
        ),
        migrations.CreateModel(
            name='FirmPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_panels', to='rengine_dashboard.firm')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rengine_dashboard.panel')),
            ],
            options={
                'unique_together': {('firm', 'panel')},
            },
        ),
        migrations.CreateModel(
            name='UserPanelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_perms', to='rengine_dashboard.membership')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rengine_dashboard.panel')),
            ],
            options={
                'unique_together': {('membership', 'panel')},
            },
        ),
    ]
