# Generated by Django 5.2.5 on 2025-08-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': '5. Category', 'verbose_name_plural': '5. Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['id'], 'verbose_name': '6. Subategory', 'verbose_name_plural': '6. Subategories'},
        ),
        migrations.AlterModelOptions(
            name='toolpage',
            options={'ordering': ['id'], 'verbose_name': '7. Information About Tool', 'verbose_name_plural': '7. Information About Tools'},
        ),
    ]
