# Generated by Django 5.2.5 on 2025-08-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolpage',
            options={'ordering': ['id'], 'verbose_name': '7. Add Tools', 'verbose_name_plural': '7. Add Tools'},
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
