# Generated by Django 5.2.5 on 2025-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_toolpage_options_alter_toolpage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingcontent',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
