# Generated by Django 5.2.5 on 2025-08-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_landingcontent_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['id'], 'verbose_name': '8. Statistic', 'verbose_name_plural': '8. Statistics'},
        ),
    ]
