# Generated by Django 5.2.5 on 2025-08-07 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_attempts_limit', models.PositiveIntegerField(default=0)),
                ('yearly_attempts_limit', models.PositiveIntegerField(default=0)),
                ('monthly_features', models.TextField(blank=True)),
                ('yearly_features', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('command', models.CharField(help_text='Command or script path', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScanFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial'), ('paused', 'Paused')], default='active', max_length=10)),
                ('auto_renew', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('manual', 'Manual'), ('internal', 'Internal')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('renewed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_left', models.PositiveIntegerField(default=0)),
                ('times_renewed', models.PositiveIntegerField(default=0)),
                ('notified_expiration', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanToolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_accesses', to='users.plan')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_accesses', to='main.toolpage')),
            ],
            options={
                'verbose_name': 'Tool Access in Plan',
                'verbose_name_plural': 'Tool Accesses in Plans',
                'unique_together': {('plan', 'tool')},
            },
        ),
        migrations.CreateModel(
            name='PlanScannerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_accesses', to='users.plan')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_accesses', to='users.scanner')),
            ],
            options={
                'verbose_name': 'Scanner Access in Plan',
                'verbose_name_plural': 'Scanner Accesses in Plans',
                'unique_together': {('plan', 'scanner')},
            },
        ),
    ]
